name: "Get useful base and head"
description: "Get the last successful commit SHA"

outputs:
  base:
    description: The value intended for use with --base or NX_BASE in all subsequent `nx affected` commands within the current workflow
    value: ${{ steps.setSHAs.outputs.base }}
  head:
    description: The value intended for use with --head or NX_HEAD in all subsequent `nx affected` commands within the current workflow
    value: ${{ steps.setSHAs.outputs.head }}

runs:
  using: "composite"
  steps:
    - name: Set base and head SHAs used for nx affected
      id: setSHAs
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        BRANCH_NAME: ${{ github.ref_name }}
      run: node "$GITHUB_ACTION_PATH/dist/index.js"

    - name: Log base and head SHAs used for nx affected
      shell: bash
      run: |
        echo "Base SHA"
        echo ${{ steps.setSHAs.outputs.base }}
        echo ""
        echo "Head SHA"
        echo ${{ steps.setSHAs.outputs.head }}
        echo ""

branding:
  icon: "terminal"
  color: "blue"